a=[["Emissions.agriculture.total","Emissions.agriculture.total_Arable.land","Emissions.agriculture.total_Soil.carbon.content_Arable.land","Emissions.agriculture.total_Soil.carbon.content_Arable.land_GEF.benefits.biodiversity","Emissions.agriculture.total_Water.withdrawal_Soil.carbon.content_Arable.land_GEF.benefits.biodiversity","Emissions.agriculture.total_Water.withdrawal_Soil.carbon.content_Arable.land_GEF.benefits.biodiversity_Energy.agriculture","Emissions.agriculture.total_pH_Water.withdrawal_Soil.carbon.content_Arable.land_GEF.benefits.biodiversity_Energy.agriculture"],["AgValueAdded","AgValueAdded_Wage.employment","AgValueAdded_Time.underemployment_Wage.employment"],["Female.labor.force","Female.labor.force_Fairtrade.org","Female.labor.force_Fairtrade.org_Agr.employment"],["City.access","City.access_Access.electricity","City.access_Foodborne.illness_Serum.retinol.deficiency","City.access_Foodborne.illness_Obesity_Serum.retinol.deficiency","City.access_Access.electricity_Foodborne.illness_Obesity_Serum.retinol.deficiency","City.access_Access.improved.water_Access.electricity_Foodborne.illness_Obesity_Serum.retinol.deficiency","City.access_Access.improved.water_Access.electricity_Price.volatility.index_Foodborne.illness_Obesity_Serum.retinol.deficiency","City.access_Access.improved.water_Access.electricity_Foodborne.illness_Diet.diversification_Crop.diversity_Obesity_Serum.retinol.deficiency","City.access_Access.improved.water_Access.electricity_Food.supply.variability_Foodborne.illness_Diet.diversification_Crop.diversity_Obesity_Serum.retinol.deficiency","City.access_Access.improved.water_Access.electricity_Price.volatility.index_Food.supply.variability_Foodborne.illness_Diet.diversification_Crop.diversity_Obesity_Serum.retinol.deficiency","Food.available_Food.consumption_City.access_Access.improved.water_Access.electricity_Food.supply.variability_Foodborne.illness_Food.loss_Diet.diversification_Obesity_Serum.retinol.deficiency","Food.available_Food.consumption_City.access_Access.improved.water_Access.electricity_Food.supply.variability_Foodborne.illness_Food.loss_Diet.diversification_Crop.diversity_Obesity_Serum.retinol.deficiency","Food.available_Food.consumption_City.access_Access.improved.water_Access.electricity_Price.volatility.index_Food.supply.variability_Foodborne.illness_Food.loss_Diet.diversification_Crop.diversity_Obesity_Serum.retinol.deficiency","Food.available_Food.consumption_City.access_Access.improved.water_Access.electricity_Price.volatility.index_Food.supply.variability_Foodborne.illness_Food.loss_Diet.diversification_Crop.diversity_Stunting_Obesity_Serum.retinol.deficiency"]]
r=[[]]
for x in a:
	 t = []
	 for y in x:
	 	 for i in r:
	 	 	 t.append(i+[y])
	 r = t
f = open("D:/ToBackup/repositories/cc-repo/sfs_project/Scripts/auxTxt.txt", "w")
z = str(r)
f.write(z)
f.close()
